[package]
name = "arcade-accelerate"
version = "1.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "arcade_accelerate"
crate-type = ["cdylib"]

[dependencies]
float_eq = "1"
pyo3 = "0.20.3"
rand = "0.8.5"
